markdown: kramdown
highlighter: rouge

permalink: /blog/:year/:month/:day/:title/

# Setup
mywebsite:
  url: http://jojozhuang.github.io
#theme: jekyll-theme-cayman

author:
  name: 'Rong Zhuang'
  email: 'jojozhuang@gmail.com'
  phone: '(+1) 650 380 4437'
  linkedin: https://www.linkedin.com/in/rongzhuang
  github: https://github.com/jojozhuang

navlist:
  - key: portfolio
    url: /portfolio
    visible: true
  - key: frontend
    url: /frontend
    visible: false
  - key: java
    url: /java
    visible: false
  - key: programming
    url: /programming
    visible: false
  - key: devops
    url: /devops
    visible: false
  - key: tutorial
    url: /tutorial
    visible: true
  - key: blog
    url: /blog
    visible: true
  - key: cv
    url: /cv
    visible: false
  - key: course
    url: /course
    visible: false
  - key: favorite
    url: /favorite
    visible: true
  - key: note
    url: /note
    visible: false
  - key: feed
    url: /blog/atom.xml"
    visible: false
  - key: more
    url: /#
    visible: false
    subkeys: note
    sublist:
      - key: note
        url: /note
      - key: programming
        url: /programming
  - key: about
    url: /about
    visible: true

collections:
  portfolio:
    output: true
  frontend:
    output: true
  java:
    output: true
  programming:
    output: true
  devops:
    output: true
  tutorial:
    output: true
  note:
    output: true
  githubpages:
    output: true

exclude: ["vendor", "_obsolete", "templates", "Gemfile", "Gemfile.lock", "sitemap.xml", "note_old.html", "favorite_old.html", "library.html", "tutorial2.html"]
#https://sacha.me/articles/jekyll-rouge/
#https://github.com/ZhengshuaiPENG/zhengshuaipeng.github.io/blob/master/_config.yml
