markdown: kramdown
highlighter: rouge

sass:
  sass_dir: public/css
  style: compressed

permalink: /blog/:year/:month/:day/:title/

# Setup
mywebsite:
  url: http://rongzhuang.me
#theme: jekyll-theme-cayman

# rss
blogtitle: Rong Zhuang's Blog

author:
  name: 'Rong Zhuang'
  email: 'jojozhuang@gmail.com'
  phone: '(+1) 650 380 4437'
  linkedin: https://www.linkedin.com/in/rongzhuang
  github: https://github.com/jojozhuang

navlist:
  - key: portfolio
    url: /portfolio
    icon: fas fa-briefcase
    visible: true
  - key: popular
    url: /popular
    icon: fas fa-fire-alt
    visible: true
  - key: tutorial
    url: /tutorial
    icon: fas fa-chalkboard-teacher
    visible: true
  - key: blog
    url: /blog
    icon: fas fa-blog
    visible: true
  - key: cv
    url: /cv
    visible: false
  - key: course
    url: /course
    visible: false
  - key: favorite
    url: /favorite
    icon: fas fa-star
    visible: true
  - key: note
    url: /note
    icon: fas fa-book-open
    visible: false
  - key: more
    url: /#
    icon: fas fa-chevron-circle-down
    visible: true
    subkeys: ["contact","rss","blank"]
    sublist:
      - key: contact
        description: Contact me
        url: /contact
        icon: fas fa-address-book
      - key: rss
        description: RSS Feed
        url: /blog/atom.xml
        icon: fas fa-rss
      - key: sitemap
        description: Sitemap
        url: /sitemap.xml
        icon: fas fa-sitemap
      - key: blank
        description: Blank Page
        url: /blank
        icon: fas fa-chalkboard
  - key: about
    url: /about
    icon: fas fa-info-circle
    visible: true

collections:
  portfolio:
    output: true
  popular:
    output: true
  tutorial:
    output: true
  githubpage:
    output: true
  note:
    output: true

exclude: ["vendor", "_obsolete", "templates", "Gemfile", "Gemfile.lock"]
#https://sacha.me/articles/jekyll-rouge/
#https://github.com/ZhengshuaiPENG/zhengshuaipeng.github.io/blob/master/_config.yml
