[build]
  command = "jekyll build"
  publish = "_site/"

[[headers]]
  for = "/public/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/public/css/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/public/js/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
